export const originalCloneContent = {
  practitioner: {
    name: "Conejo Valley Family Counseling",
    tagline: "Therapy in Newbury Park, CA",
    location: "Newbury Park, CA",
    address: {
      street: "925 Broadbeck Dr Suites 200 and 225",
      city: "Newbury Park",
      state: "CA",
      zip: "91320",
      full: "925 Broadbeck Dr Suites 200 and 225, Newbury Park, CA 91320",
    },
    email: "info@conejovalleycounseling.com",
    phone: "805.242.3120",
    logo: "/assets/conejo/Conejo_Valley_Counseling_Logo.png",
  },
  navigation: [
    { label: "About", href: "#about" },
    { label: "Specialties", href: "#specialties" },
    { label: "Methods", href: "#methods" },
    { label: "FAQs", href: "#faqs" },
    { label: "Contact", href: "#contact" },
  ],
  hero: {
    eyebrow: "ONLINE & IN-PERSON COUNSELING IN NEWBURY PARK & ACROSS CA",
    title: "Rebuild your foundation on solid ground and finally begin to thrive.",
    subtext: "Specialized therapy for adults, couples, teens, and children to reflect, heal, and grow.",
    primaryCta: "Book an Appointment",
    image1: "/assets/conejo/Jennifer_A_-_Images__2866_29.jpg",
    image2: "/assets/conejo/Jennifer_A_-_Images__2867_29.jpg",
  },
  empathy: {
    heading: "You’re holding onto hope that life can be better than it is right now.",
    paragraphs: [
      "At Conejo Valley Family Counseling we want to make that hope a reality.",
      "Whether you're an adult seeking personal growth, looking to work through your trauma, a couple working on your relationship, or a parent looking for support for your child, we provide a compassionate and safe space to help you navigate all of life’s ups and downs.",
      "First and foremost, we believe what you’re going through is real, valid, and worthy of support. Our team offers clients in the Newbury Park area and across CA an environment to discover a new life and a deeper sense of self in the midst of their struggles. As we tap into the power of connection and understanding, you can find your footing again and take a transformative path forward.",
    ],
    image: "/assets/conejo/Jennifer_A_-_Images__283_29.jpg",
  },
  whoWeHelp: {
    heading: "Who we help",
    items: [
      {
        title: "Adults",
        description: "Feeling stuck or overwhelmed? We help adults find clarity, build resilience, and move forward with confidence by addressing the root causes of anxiety, stress, and emotional pain.",
        image: "/assets/conejo/Jennifer_A_-_Images__288_29.jpg",
      },
      {
        title: "Couples",
        description: "Relationships require effort, and we’re here to help you strengthen yours. We guide couples through challenges like communication breakdowns and trust issues, helping you rebuild intimacy and strengthen your relationship.",
        image: "/assets/conejo/Jennifer_A_-_Images__289_29.jpg",
      },
      {
        title: "Children & Teens",
        description: "Kids need support, too. We help them process big emotions, cope with challenging family situations, build coping skills, and feel understood, while also working closely with their parents to create a nurturing environment.",
        image: "/assets/conejo/Jennifer_A_-_Images__2810_29.jpg",
      },
    ],
  },
  quoteBanner1: {
    quote: "You deserve a place where your story is heard, valued, and understood. Nothing will be too heavy for us to carry together.",
    image: "/assets/conejo/Jennifer_A_-_Images__282_29.png",
  },
  areasOfExpertise: {
    heading: "Our areas of expertise",
    tags: [
      "Dissociation",
      "Trauma",
      "Family conflict",
      "Special needs parenting",
      "Depression",
      "Marriage",
      "Anxiety",
      "Relationships",
      "Children",
      "Teens",
      "Intimacy & connection",
      "…and more.",
    ],
  },
  howWeWork: {
    eyebrow: "HOW WE WORK",
    heading: "We’re here to make a difference.",
    paragraphs: [
      "The clients we work with are balancing so many things at once, it’s often hard for them to put themselves first.",
      "Here, your needs are always top priority. Our team takes the time to deeply listen to our clients in order to truly understand their story and their struggles. We recognize that no two people are the same and that personalized therapy means an intentional, tailored approach. (You won’t find anything “one-size-fits-all” here.) If you’re ready to do the work, we’re ready to help.",
      "Sometimes we may gently challenge you to look at things differently and other times we may explore your emotions, all while encouraging you to practice what you’ve learned in your daily life. We take what we do seriously because we know how important it is for you to heal from what’s hurting you, discover a fulfilling life, and build meaningful relationships. Our goal is to walk alongside you in this journey, offering support and guidance as you uncover your strengths and embrace what the future can hold for you.",
    ],
    buttonText: "Learn more about us",
    image: "/assets/conejo/Jennifer_A_-_Images__286_29.jpg",
  },
  quoteBanner2: {
    quote: "Honoring where you’ve been & helping shape where you’re headed.",
    image: "/assets/conejo/Jennifer_A_-_Images__285_29.jpg",
  },
  specialties: {
    heading: "Our specialties include…",
    services: [
      {
        id: "trauma",
        title: "Trauma",
        badge: "Specialty",
        shortDesc: "We don’t always know when and how we’ve experienced trauma. In therapy, we’ll work together to help you process your past, understand what’s causing you to stay “stuck,” and regain a sense of safety, control, and hope. You don’t have to carry your burdens alone.",
        fullDesc: "We don’t always know when and how we’ve experienced trauma. In therapy, we’ll work together to help you process your past, understand what’s causing you to stay “stuck,” and regain a sense of safety, control, and hope. You don’t have to carry your burdens alone.",
        image: "/assets/conejo/Jennifer_A_-_Images__288_29.jpg",
        slug: "#contact",
      },
      {
        id: "dissociation",
        title: "Dissociation",
        badge: "Specialty",
        shortDesc: "The feeling of losing time, hearing conflicting voices, or questioning your sense of self can be overwhelming. In therapy, we’ll help you understand these experiences, recognize your own triggers, and create a sense of balance and identity so that you can feel more grounded.",
        fullDesc: "The feeling of losing time, hearing conflicting voices, or questioning your sense of self can be overwhelming. In therapy, we’ll help you understand these experiences, recognize your own triggers, and create a sense of balance and identity so that you can feel more grounded.",
        image: "/assets/conejo/Jennifer_A_-_Images__289_29.jpg",
        slug: "#contact",
      },
      {
        id: "emdr",
        title: "EMDR",
        badge: "Specialty",
        shortDesc: "Eye Movement Desensitization and Reprocessing (EMDR) is a powerful therapeutic technique that helps process and heal trauma by reworking how painful memories are stored in your brain. This allows you to find relief and move toward lasting healing.",
        fullDesc: "Eye Movement Desensitization and Reprocessing (EMDR) is a powerful therapeutic technique that helps process and heal trauma by reworking how painful memories are stored in your brain. This allows you to find relief and move toward lasting healing.",
        image: "/assets/conejo/Jennifer_A_-_Images__2810_29.jpg",
        slug: "#contact",
      },
      {
        id: "special-needs-parenting",
        title: "Special Needs Parenting",
        badge: "Specialty",
        shortDesc: "Parenting a child with special needs presents unique challenges and complex emotions. We provide compassionate support through lived experience and expertise to help you navigate this journey with tools, understanding, and self-care.",
        fullDesc: "Parenting a child with special needs presents unique challenges and complex emotions. We provide compassionate support through lived experience and expertise to help you navigate this journey with tools, understanding, and self-care.",
        image: "/assets/conejo/Jennifer_A_-_Images__286_29.jpg",
        slug: "#contact",
      },
    ],
  },
  bookingCta: {
    eyebrow: "SCHEDULE AN APPOINTMENT",
    heading: "Find a therapist who is the right fit for you.",
    paragraphs: [
      "Coming to therapy is a courageous decision, and connecting with the right kind of therapist makes all the difference. We understand that your journey is personal, and we're here to support you with care and understanding every step of the way.",
      "Click the button below to schedule an appointment.",
    ],
    ctaButton: "Book now",
    image1: "/assets/conejo/Jennifer_A_-_Images__2812_29.jpg",
    image2: "/assets/conejo/Jennifer_A_-_Images__2811_29.jpg",
  },
  footer: {
    aboutText: "We want to make getting started simple. You’re welcome to come into our office in Newbury Park or schedule virtual appointments from anywhere in CA—whatever works best for you.",
    serviceAreas: "Serving Thousand Oaks, Westlake Village, Camarillo, Moorpark, & Simi Valley",
    disclaimer: "Terms | Privacy Policy | Disclaimer | Website by Walker Strategy Co.",
  },
};
